# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
# list of datasources to insert/update depending
# what's available in the database
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
# - name: Jaeger
#   uid: webstore-traces
#   type: jaeger
#   url: http://jaeger:16686/jaeger/ui
#   editable: true
#   isDefault: false  