version: '3.8'
services:
  cache:
    container_name: test-redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes: 
      - redis-data:/data
    networks:
      - wcm-network
volumes:
  redis-data:
    external: true
networks:
  wcm-network:
    external: true