# oc kustomize overlays/redhat -o redhat-deployment.yaml
# oc apply -k  $(System.ArtifactsDirectory)/my-camel-integrator/src/main/ocp/overlays/redhat
# cd overlays/redhat
# kustomize edit set image my-camel-integrator=my-camel-integrator:v1-05-30-20-1
# oc apply -k  overlays/redhat
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frank-x-li-dev
namePrefix: "my-camel-"
commonLabels:
  variant: my-sandbox
  app: my-camel-integrator
patches:
- target:
    group: "" # core
    version: v1
    kind: ConfigMap
    name: integrator-env
  path: env-configmap-patch.yaml
- target:
    group: "autoscaling"
    version: v2
    kind: HorizontalPodAutoscaler
    name: integrator
  path: hpa-patch.yaml 
- target:
    group: "apps"
    version: v1
    kind: Deployment
    name: integrator
  path: deployment-patch.yaml   
- target:
    group: "route.openshift.io"
    version: v1
    kind: Route
    name: integrator
  path: route-patch.yaml   
resources:
- ../../base/http
images:
  - name: integrator
    newName: my-camel-integrator
    newTag: "v1-06-06-23-14-06"
