replicaCount: 1
imagePullSecrets:
  - name: myregistry.azurecr.io
nameOverride: "my-camel-integrator"
fullnameOverride: "my-camel-integrator"
springProfiles: sandbox
podSecurityContext: {}
spring_config:
  application_yml: |-
    # to configure logging levels
    logging:
      level:
        org.springframework: ${APP_LOG_LEVEL:INFO}
        org.apache.camel.spring.boot: ${APP_LOG_LEVEL:INFO}
        io.atlasmap: ${APP_LOG_LEVEL:INFO}
        org.apache.camel.impl: ${APP_LOG_LEVEL:INFO}
extraVolumes:
extraVolumeMounts:          
# In our pipeline the image is set after the validation, without this placeholder the validation would fail
image:
  registry: myregistry.azurecr.io
  name: my-camel-integrator
  tag: v1-06-06-23-14-06
  pullPolicy: IfNotPresent


container:
  containerPort: 8443
  actuatorPort: 8443
  targetPort: 8443
  # nodePort:
  schema: HTTPS
  liveness:
    path: /actuator/health
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readiness:
    path: /actuator/health
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


service:
  type: ClusterIP
#  port: 8443
#  targetPort: 8443


route:
  enabled: true
  annotations: {}
  host: my-camel-integrator-my-sandbox.cluster.local
  tls:
    termination: reencrypt

resources:
  limits:
    # Since the Spring Boot Maven Plugin builds our containers via the Java Buildpack, we need around
    # 700 MB, otherwise the container fails to start with: "allocated memory is greater..."
    # See https://twitter.com/nebhale/status/1281646532295454720
    # And https://github.com/cloudogu/gitops-playground/pull/116#issuecomment-1609184514
    # In exchange, we get the JVM set up with best practice settings in memory regions.
    # Hopefully getting less trouble with ops.
    # https://www.cloudfoundry.org/blog/just-released-java-buildpack-4-0/
    # Depending on the number of classes in our apps we might have to increase this later.
    memory: 700Mi
  requests:
    memory: 700Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false