ingressGateways:
  # Enable ingress gateways.
  enabled: true
  defaults:
    # Since there is only one node in minikube,
    # set affinity to null so during an upgrade
    # two ingress gateway pods can run on the
    # same node.
    affinity: null

  gateways:
    - name: ingress-gateway
      service:
        # Set the service type to LoadBalancer so
        # that you can access it through minikube tunnel.
        type: LoadBalancer
        # Access the gateway on port 8080