server:
  port: 10000
  servlet.context-path: /my-camel/console
  shutdown: graceful
  # Adding SameSite=Strict for session cookie is recommended
  servlet.session.cookie.same-site: strict
management:
  server:
    port: 10001
    base-path: /my-camel/console
  endpoints:
    web.exposure.include: hawtio,jolokia
    #  Actuator Enpoints exposure for the spring-boot plugin
    jmx.exposure.include: health,info,loggers,httpexchanges

    # Information for Spring Boot Info endpoint
  info:
    env.enabled: true
    java.enabled: true

info.app.name: Hawtio Camel Admin Console

spring:
  jmx.enabled: true

logging:
  level.io.hawt: INFO
  level.org.springframework: WARN

camel:
  springboot:
    name: MyCamelAdminConsole

    # Uncomment these properties to enable the Camel plugin Trace tab
    # tracing: true
    # backlog-tracing: true
    # use-breadcrumb: true

quartz:
  cron:  0 0 0/1 * * ?
  # quartz.repeatInterval = 10000
  repeatInterval: 1000000

hawtio:
  authenticationEnabled: false
  disableProxy: false
  proxyAllowlist: r:.*-my-camel\.apis\.com
#
# Hawtio properties to change the behaviours for HTTP headers
# (Hawtio version >2.15.1)
#

# By default, Access-Control-Allow-Origin is no more sent.
# To send the HTTP header, uncomment the following line.
#  http:
#    enableCORS: true

# When hawtio.http.enableCORS=true is set, Hawtio by default sends:
#
#   Access-Control-Allow-Origin: *
#
# You can customise the header value with the following property.
#  http.accessControlAllowOrigin: https://example.com

# By default, Hawtio sends the following HTTP headers:
#
#   X-Frame-Options: DENY
#   Content-Security-Policy: frame-ancestors 'none'
#
# By uncommenting the following line, these headers are changed like these
# (the behaviour in 2.15.1 and before):
#
#   X-Frame-Options: SAMEORIGIN
#   Content-Security-Policy: frame-ancestors 'self'
#
#    allowXFrameSameOrigin: true

# By default, Hawtio sends the following HTTP header:
#
#   Referrer-Policy: strict-origin
#
# You can customise the header by setting the following property.
#    referrerPolicy: no-referrer
my-camel:
  feign.logger.level: FULL
  validate.api.request: false
  webclient:
    connection-timeout-mills: 20000
    read-timeout-mills: 20000
    mac-connection: 300
  refresh-url:
    - applicationName: app1
      refreshUrl: http://app1/actuator/refresh
    - applicationName: app2
      refreshUrl: http://app2/actuator/refresh
    - applicationName: app3
      refreshUrl: http://app3/actuator/refresh
  circuitbreaker:
    api-client:
      registrerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 50
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 5
      minimumNumberOfCalls: 20
      permittedNumberOfCallsinHalfOpenState: 10
      waitDurationInOpenState: 60
