
server:
  port: 8888
  shutdown: graceful
  servlet.context-path: /my
spring:
  profiles:
    active:
      - jdbc
      - ${SPRING_PROFILES_ACTIVE:local}  
  application:.name: my-camel-config-server
  datasource:
   platform: oracle
   # url: jdbc:h2:mem:configdb
   # driver-class-name: org.h2.Driver
   # username: sa
   # password: sa
   # platform: postgresql
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
   driver-class-name: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521/FREE
   username: C##Camel
   password: Passw0rd
   hikari:
     connection-timeout: 5000
     maximum-pool-size: 10
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT PROP_KEY, PROP_VALUE from APP_PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1
        prefix: config 
  security:
    user:
      name: s2i
      password: s2i
  liquibase.enabled: false
  liquibase.contexts: ${SPRING_PROFILES_ACTIVE:local}
liquibase.change-log: classpath:/db/changelog/db.changelog-master.yaml      
management:
  endpoints:
    health:
      enabled: true
      show-details: always
      # expose liveness/readiness probes
      probes:
        enabled: true
    web:
      # base-path: 
      exposure.include: health,info,hawtio,jolokia
  # Information for Spring Boot Info endpoint
  info:
    env.enabled: true
    java.enabled: true
    app.name: ${spring.application.name}
  server.port: ${server.port}

logging.level:
  com.example: DEBUG
  io.hawt: INFO
  org.springframework: WARN

camel:
  springboot.name: ${spring.application.name}

# Uncomment these properties to enable the Camel plugin Trace tab
#camel.springboot.tracing=true
#camel.springboot.backlog-tracing=true
#camel.springboot.use-breadcrumb=true

hawtio:
  authenticationEnabled: false
  http:
    enableCORS: true
    proxyAllowlist: "*"      
