
server:
  port: 8080
  shutdown: graceful
  servlet.context-path: /my
spring:
  profiles:
    active:
      - jdbc
      - ${SPRING_PROFILES_ACTIVE:local}  
  application:.name: my-camel-config-server
  datasource:
   platform: oracle
   # url: jdbc:h2:mem:configdb
   # driver-class-name: org.h2.Driver
   # username: sa
   # password: sa
   # platform: postgresql
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
   driver-class-name: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521/FREE
   username: C##CAMEL
   password: Passw0rd
   hikari:
     connection-timeout: 5000
     maximum-pool-size: 10
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT PROP_KEY, PROP_VALUE from APP_PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1
        prefix: config 
  security:
    user:
      name: config
      password: config
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/2e9fde3a-38ec-44f9-8bcd-c184dc1e8033/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
#            client-id: "6035bfd4-22f0-437c-b76f-da729a916cbf"
#            client-secret: "fo28Q~-aLbmQvonnZtzbgtSiqYstmBWEmGPAodmx"
            client-id: your-client-id
            client-secret: your-secret-id
            scope:
              - openid
              - email
              - profile
  liquibase.enabled: false
  liquibase.contexts: ${SPRING_PROFILES_ACTIVE:local}
liquibase.change-log: classpath:/db/changelog/db.changelog-master.yaml      
management:
  endpoints:
    health:
      enabled: true
      show-details: always
      # expose liveness/readiness probes
      probes:
        enabled: true
    web:
      # base-path: 
      exposure.include: health,info,hawtio,jolokia
  # Information for Spring Boot Info endpoint
  info:
    env.enabled: true
    java.enabled: true
    app.name: ${spring.application.name}
  server.port: ${server.port}

logging.level:
  com.example: DEBUG
  io.hawt: INFO
  org.springframework: WARN

camel:
  springboot.name: ${spring.application.name}

# Uncomment these properties to enable the Camel plugin Trace tab
#camel.springboot.tracing=true
#camel.springboot.backlog-tracing=true
#camel.springboot.use-breadcrumb=true

hawtio:
  authenticationEnabled: false
  http:
    enableCORS: true
    proxyAllowlist: "*"      

# Group mapping
my:
  jwt:
    authorization:
      group-to-authorities:
        "ceef656a-fca9-49b6-821b-f7543b7065cb": BAELDUNG_RW
        "eaaecb69-ccbc-4143-b111-7dd1ce1d99f1": BAELDUNG_RO,BAELDUNG_ADMIN