apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: integrator
# namePrefix: "my-"
#nameSuffix: "-integrator"

#commonAnnotations:
#  xxx: yyyy
resources:
  - route.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - env-configmap.yaml
  - spring-configmap.yaml