version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nextauth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wcm-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "18181:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - wcm-network  
volumes:
  postgres-data:
    external: true
  pgadmin-data:
    external: true
networks:
  wcm-network:
    external: true
