global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  # - job_name: loki
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: [loki:3100]
  # - job_name: 'tempo'
  #   static_configs:
  #   - targets: ['tempo:3200']
  - job_name: otel
    honor_labels: true
    static_configs:
    - targets:
      - 'otel-collector:9464'
  - job_name: otel-collector
    static_configs:
    - targets:
      - 'otel-collector:8888'